serviceAccount:
  create: true

containers:
  image: easzlab.io.local:5000/kuberos
  tag: latest
  pullPolicy: IfNotPresent

sidecar:
  image: easzlab.io.local:5000/krb_sidecar
  tag: latest
  pullPolicy: IfNotPresent

krb5:
  default_ccache_path: /tmp/ccache
  default_ccache_file: krb5kdc_ccache

client:
  secret_name: "krb5-keytab"
